name: "user_web"

server:
  host: "127.0.0.1"
  port: "8098"

logger:
  level: "info"
  development: "true"
  Encoding: "console"
  EncoderConfig: "pro"
  OutputPaths: "stderr"

user_srv:
  host: "127.0.0.1"
  port: "8088"
