name: "user_web"

server:
  host: "127.0.0.1"
  port: "8098"

logger:
  level: "debug"
  development: "true"
  Encoding: "console"
  EncoderConfig: "dev"
  OutputPaths: "stderr"

user_srv:
  host: "127.0.0.1"
  port: "8088"
